### ISSUE TITLE
Source map support?

### ISSUE THREAD

**Issue by richarddd** [awslabs/aws-crt-nodejs#358] opened 2022-10-09 19:41 UTC
Im getting errors when using aws-crt with aws-iot-device-sdk-v2. When using webpack, I'm getting a lot of `Error: ENOENT: no such file or directory` since webpack tries to resolve the original sources from the `node_modules/aws-crt/lib/` directory.

**Comment by bretambrose** [comment] 2022-10-10 15:02
I don't know anything about webpack, but the v2 SDK has multiple browser samples (https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser/) that I've been able to use just fine.  Is there any difference in their webpack configs that might account for what you're running into?

**Comment by richarddd** [comment] 2022-10-14 05:34
@bretambrose i have created a reproducer repo here:
https://github.com/richarddd/react-aws-iot-device-sdk-v2
Please see all the warnings of missing typescript files when running `yarn start` or `npm run start`

**Comment by richarddd** [comment] 2022-10-16 19:19
> non-browser environments

Not quite sure i follow what you mean by non-browser? This reproducer repo is React for browser only

**Comment by bretambrose** [comment] 2022-10-17 15:52
My mistake, was thinking more electron there I guess.

**Comment by croraf** [comment] 2022-12-06 23:17
I experience the same issue with create-react-app (+ craco), that is same setup.

But not with https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser/pub_sub 

The cause might be that create-react-app doesn't use `ts-loader` but instead `babel-loader` with some custom babel preset.

**Comment by bretambrose** [comment] 2023-03-23 22:15
This should be addressed in v1.15.3

**Closed by bretambrose** 2023-03-23 22:15 UTC
